### ISSUE TITLE
win10 下面官方栗子会报错

### ISSUE THREAD

**Issue by xhochipe** [chfw/pyecharts-snapshot#6]
'phantomjs' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "H:/project/python/web/xmshop/test/2.py", line 13, in <module>
    make_a_snapshot('render2.html', 'snapshot.png')
  File "D:\Program Files (x86)\python\pythonenv\lib\site-packages\pyecharts_snapshot\main.py", line 60, in make_a_snapshot
    base64_imagedata = content.split(',')[1]
IndexError: list index out of range

**Comment by chfw** [comment]
https://github.com/chfw/pyecharts-snapshot/issues/3
