### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by zixuzhang** [chfw/pyecharts-snapshot#7]
zxjd@zxjd-OptiPlex-7040:~$ snapshot render.html 
Traceback (most recent call last):
  File "/usr/local/bin/snapshot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pyecharts_snapshot/main.py", line 35, in main
    make_a_snapshot(file_name, output, delay=delay)
  File "/usr/local/lib/python2.7/dist-packages/pyecharts_snapshot/main.py", line 54, in make_a_snapshot
    proc_params, stdout=subprocess.PIPE, shell=shell_flag)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zixuzhang** [comment]
安装Phantomjs后可以啦
